### PR TITLE
Porting ALICE-specific changes

### PR DESCRIPTION
**Pull request by aalkin**

### CODE REVIEW

**Comment by aalkin** [comment]
@ktf here are the changes. Let's wait for the tests to run before merging, though, maybe I have missed something.

**Comment by pzhristov** [comment]
There is at least this issue:
/Users/phristov/alisw/sw/BUILD/8563d9b46564fe5c75f04c95c2f33b3c09dc62c8/arrow/src_tmp/cpp/src/gandiva/precompiled/arithmetic_ops.cc:265:1: error: functions that differ only in their return type cannot be overloaded
BITWISE_NOT(uint64)

**Comment by aalkin** [comment]
@pzhristov that one I already fixed, but there is gandiva-internal-test failing and I can't seem to find the reason. On top of that I cannot build arrow tests locally, neither with brew-installed google test, nor the one from alibuild. Also the latter does not seem to have an environment config.

**Comment by pzhristov** [comment]
@aalkin Thanks, at least it compiles now.

**Comment by aalkin** [comment]
@ktf @pzhristov I think I've fixed issues introduced by my code, there is still s3fs test failing, and some of the CI tests fail at installing dependencies but all that is not relevant for us. I believe this is good to go.

**Comment by pzhristov** [comment]
@aalkin Thanks, I will test it on CC7/CC8, where we had issues with 3.0.0.

**Comment by ktf** [comment]
I've merged this so that we can try in the CI as well.

**Pull request merged**
